version: '3'
services:
    mindbehind_backend:
        restart: always
        container_name: mindbehind_dev
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - ./src:/app/src
            - ./package.json:/app/package.json
            - ./tsconfig.json:/app/tsconfig.json
        ports:
            - '3000:3000'
        depends_on:
            mysql:
                condition: service_healthy
        env_file:
            - ./env/.env

    mysql:
        image: mysql:8.4
        container_name: mysql_dev
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mindbehind
        ports:
            - '3306:3306'
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
            start_period: 5s
            interval: 5s
            timeout: 5s
            retries: 30

    adminer:
        image: adminer
        container_name: adminer_dev
        restart: always
        ports:
            - '8080:8080'
